wandb_version: 1

model_name:
  desc: null
  value: bert-base-uncased
labels:
  desc: null
  value:
  - Balling
  - Bead Cut
  - Humping
  - Lack of fusion
  - Normal
max_length:
  desc: null
  value: 256
threshold:
  desc: null
  value: 0.5
save_path:
  desc: null
  value: ./saved_models
best_model_path:
  desc: null
  value: null
data_dir:
  desc: null
  value: ./data
train_file:
  desc: null
  value: bert_train_waam_cls_p1.json
val_file:
  desc: null
  value: bert_val_waam_cls_p1.json
test_file:
  desc: null
  value: bert_test_waam_cls_p1.json
batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 15
learning_rate:
  desc: null
  value: 3e-5
seed:
  desc: null
  value: 42
device:
  desc: null
  value: cuda
wandb_project:
  desc: null
  value: bert-multilabel
_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.52.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1748941074.1602
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.11
      5: 0.15.12
      6: 4.52.4
      8:
      - 5
      13: linux-x86_64
