
model_name: "bert-base-uncased"
max_len: 256

# 모델 저장 경로
save_path: "./saved_models_heat"
best_model_path: "./saved_models_heat/bert-base-uncased/0615_2044_epoch15_valLoss7349.6606_rmse_85.7302.pth"   

# 데이터 경로 설정
data_dir: "../data/merged"                
train_file: "train_task02_merged_train.json"            
val_file: "train_task02_merged_train_val.json"                                         
test_file: "test_task02_merged.json"        

# 학습 설정
batch_size: 8       # 데이터 작고, 클래스 불균형 → 작은 배치 사이즈로 더 자주 업데이트
epochs: 25
learning_rate: 3e-5
seed: 42
device: "cuda"  
best_epoch : 30
n_splits : 5
patience : 10

# wandb 설정
wandb_project: "bert_regression_project"