
model_name: "roberta-base"
max_len: 256

# 모델 저장 경로
save_path: "./saved_models_e"
best_model_path: "0615_2108_epoch27_valLoss48413468.0000_rmse_6957.9787.pth"   


# 데이터 경로 설정
data_dir: "../data/merged"                
train_file: "train_task02_e_merged_train.json"            
val_file: "train_task02_e_merged_train_val.json"                                         
test_file: "test_task02_e_merged.json"        

# 학습 설정
batch_size: 8       # 데이터 작고, 클래스 불균형 → 작은 배치 사이즈로 더 자주 업데이트
epochs: 50
learning_rate: 3e-5
seed: 42
device: "cuda"  
best_epoch : 30
n_splits : 5
patience : 10

# wandb 설정
wandb_project: "bert_regression_project"