data:
  train_path: ./data/train.json
  test_path: ./data/test.json
  max_len: 128

training:
  num_folds: 5
  batch_size: 16
  epochs: 3
  saved_models_dir: ./saved_models

model:
  final_model_dir: ./saved_models/final_model
  model_name : 